### ISSUE TITLE
Ease load on archive.org by downloading files from a local repository

### ISSUE THREAD

**Issue by stefanerwinmayer** [MAME-GETTER/MiSTer_MAME_SCRIPTS#18]
Would it be possible for the script to look for the files on a local network folder to ease the load on archive.org?

**Comment by MAME-GETTER** [comment]
This is an interesting idea but why wouldn't the use just copy their own files over to MiSTer? 

if your looking to ease load on AO would a torrent solution be better.

**Comment by stefanerwinmayer** [comment]
The problem is that one usually has a full MAME set with thousands of files and it isn't clear which files need to be copied.

**Comment by MAME-GETTER** [comment]
So the bigger issues is mameversion. 

Properly formatted MRAs will contain what <mameversion/> (i.e. what set version: .206, .217 .221, ect) the core needs. 

The getter scripts figure this out and pull from the proper version.

Because of this I think it's unlikely that a user would have all the different sets.

Closing.

**Comment by stefanerwinmayer** [comment]
No problem. Thanks for considering and keep up the good work.
