### ISSUE TITLE
Curl timeout

### ISSUE THREAD

**Issue by SUNExerion** [MAME-GETTER/MiSTer_MAME_SCRIPTS#24]
Can the CURL timeout be increased a bit? I receive this with the biggest files of the bunch:

MRA: ../_Arcade/Street Fighter II  The World Warrior -World 910522-.mra
ZIP: sf2.zip
MAME version not listed in MRA or there is no download source for the version, downloading from .217 set
curl: (28) Operation timed out after 119122 milliseconds with 27836150 bytes received
curl: (28) Operation timed out after 119105 milliseconds with 28327542 bytes received
curl: (28) Operation timed out after 119183 milliseconds with 25525860 bytes received
curl: (28) Operation timed out after 119143 milliseconds with 28950134 bytes received

MRA: ../_Arcade/Street Fighter II'  Champion Edition -World 920513-.mra
ZIP: sf2ce.zip
MAME version not listed in MRA or there is no download source for the version, downloading from .217 set
curl: (28) Operation timed out after 119212 milliseconds with 27623138 bytes received
curl: (28) Operation timed out after 119118 milliseconds with 28638790 bytes received
curl: (28) Operation timed out after 117669 milliseconds with 27770452 bytes received
curl: (28) Operation timed out after 119252 milliseconds with 28245566 bytes received

**Comment by MAME-GETTER** [comment]
curl  timeout is set to about 120 seconds.  I  do not see a need to increase it. 

You need a better internet connection or try at another time as archive.org may be congested.

**Comment by movisman** [comment]
Hello!

I just wanted to add a note to this, as I came up against this timeout a couple of times recently when reinstalling and tweaking my MiSTer instance from fresh. The sf2 and sf2ce files were specifically affected like the above user. They are much larger than the other files at around 32mb and 42mb respectively. The next largest file that the MAME/HBMAME downloader pulls is less than half that size. However, with CPS2 on the horizon, I would imagine there will be a few more zip files 'on the larger side' to download in the future, especially as they will be from a merged set.
I have a stable, fast network connection and am running my initial MiSTer update using ethernet, so speed on my side is no problem.

What I noticed, is archive.org is often throttling or experiencing slow speeds, and as such the larger files don't get chance to download in full on the 'first run', due to the aforementioned timeout. As such, you are left with incomplete zip files, which also don't get overwritten or replaced with each subsequent update run, because technically the files exist and the updater does not overwrite existing files. This then causes issues when games are launched, etc.

If the script is trying to pull a 40mb file, but it's only transferring at, say, 30kb a sec, I don't think a timeout should stop the download from actually finishing if it is legitimately transferring - albeit relatively slowly. That's what seems to happen, would that be right?

In my case, it was easy to resolve - I remove the last_run file, and delete sf2 and sf2ce from the file system. This forces a full resync - I re-run the updater and during this process it will try to download those files again.

What is curious though (and i'm not sure why this is), on the very first run of the script it gives a lot less info on the screen as each file is downloaded (no speed, time, bytes transferred etc). This might be by design to cut down on console output/log size. However, what I noted - it is only during this initial first time run the curl timeout was an occasional problem for me.

On any type of subsequent run (including if you do a full clearout of all MAME roms and delete the last_run file to force a resync), when the script runs, you get more info as each file downloads (time elapsed, bytes transferred etc). But in my testing, nothing "times out" unexpectedly. Archive.org was still giving me awful speeds on a subsequent run, and the sf2 and sf2ce files still took 4-5 minutes each to download. So, in theory they should have timed out? But they just sat there happily transferring until each had finished. Maybe there is some different behaviour when the script is first run vs. subsequent runs? I really don't know.

I wanted to bring it up because with cores like CPS2 soon to be released to the public, I can see larger roms needing to be downloaded by the script. This could mean that when people first install their MiSTer, they then run something like the update_all script for the first time. Then, if archive.org just happens to be on the go-slow or throttling (irrelevant of the users internet speed), it's possible a timeout will kick in if a file doesn't finish downloading within a certain timeframe. This means files do not download properly and the user is left with an incomplete zip. This could be a more common occurrence when you have a lot more ROMs to download which are over 25/30mb, or 40mb+ in size. The chances of a timeout are higher.

Hopefully the above makes sense. I might not be explaining things well, or perhaps I am misunderstanding how it works. I don't want to waste your time, but I think something is not quite right. Thanks a lot for reading - maybe you would consider having a quick look at this, or possibly reopening the issue. Perhaps the timeout can be extended somewhat if you are willing to do so, to cover off those larger ROMs.

Thanks very much!
